aliases:
    fleeks: cd ~/.local/share/fleek
    latest-fleek-version: nix run https://getfleek.dev/latest.tar.gz -- version
    update-fleek: nix run https://getfleek.dev/latest.tar.gz -- update
allow_broken: false
auto_gc: true
bling: high
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - asciiquarium
    - vim
    - glow
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      home: ""
      hostname: debian
      os: linux
      user:
        email: V@fbi.gov
        name: V
        ssh_private_key_file: ~/.ssh/id_rsa
        ssh_public_key_file: ~/.ssh/id_rsa.pub
        username: vera
      username: vera
track: nixos-unstable
unfree: true
users: []
